// Code generated by MockGen. DO NOT EDIT.
// Source: segment.go
//
// Generated by this command:
//
//	mockgen -source segment.go -destination=./mocks/mock_segment.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/loungeup/go-loungeup/client/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSegmentsManager is a mock of SegmentsManager interface.
type MockSegmentsManager struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentsManagerMockRecorder
	isgomock struct{}
}

// MockSegmentsManagerMockRecorder is the mock recorder for MockSegmentsManager.
type MockSegmentsManagerMockRecorder struct {
	mock *MockSegmentsManager
}

// NewMockSegmentsManager creates a new mock instance.
func NewMockSegmentsManager(ctrl *gomock.Controller) *MockSegmentsManager {
	mock := &MockSegmentsManager{ctrl: ctrl}
	mock.recorder = &MockSegmentsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentsManager) EXPECT() *MockSegmentsManagerMockRecorder {
	return m.recorder
}

// BuildESQuery mocks base method.
func (m *MockSegmentsManager) BuildESQuery(selector *models.SegmentSelector, params *models.SearchCriterion) (*models.BuildSegmentESQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildESQuery", selector, params)
	ret0, _ := ret[0].(*models.BuildSegmentESQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildESQuery indicates an expected call of BuildESQuery.
func (mr *MockSegmentsManagerMockRecorder) BuildESQuery(selector, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildESQuery", reflect.TypeOf((*MockSegmentsManager)(nil).BuildESQuery), selector, params)
}
