// Code generated by MockGen. DO NOT EDIT.
// Source: currency.go
//
// Generated by this command:
//
//	mockgen -source currency.go -destination=./mocks/mock_currency.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/loungeup/go-loungeup/client/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCurrencyClient is a mock of CurrencyClient interface.
type MockCurrencyClient struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyClientMockRecorder
	isgomock struct{}
}

// MockCurrencyClientMockRecorder is the mock recorder for MockCurrencyClient.
type MockCurrencyClientMockRecorder struct {
	mock *MockCurrencyClient
}

// NewMockCurrencyClient creates a new mock instance.
func NewMockCurrencyClient(ctrl *gomock.Controller) *MockCurrencyClient {
	mock := &MockCurrencyClient{ctrl: ctrl}
	mock.recorder = &MockCurrencyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyClient) EXPECT() *MockCurrencyClientMockRecorder {
	return m.recorder
}

// ReadCurrencyRates mocks base method.
func (m *MockCurrencyClient) ReadCurrencyRates(selector *models.CurrencyRatesSelector) (*models.CurrencyRates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCurrencyRates", selector)
	ret0, _ := ret[0].(*models.CurrencyRates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCurrencyRates indicates an expected call of ReadCurrencyRates.
func (mr *MockCurrencyClientMockRecorder) ReadCurrencyRates(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCurrencyRates", reflect.TypeOf((*MockCurrencyClient)(nil).ReadCurrencyRates), selector)
}
