// Code generated by MockGen. DO NOT EDIT.
// Source: entity.go
//
// Generated by this command:
//
//	mockgen -source entity.go -destination=./mocks/mock_entity.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	json "encoding/json"
	reflect "reflect"

	resmodels "github.com/loungeup/go-loungeup/resmodels"
	gomock "go.uber.org/mock/gomock"
)

// MockEntitiesManager is a mock of EntitiesManager interface.
type MockEntitiesManager struct {
	ctrl     *gomock.Controller
	recorder *MockEntitiesManagerMockRecorder
	isgomock struct{}
}

// MockEntitiesManagerMockRecorder is the mock recorder for MockEntitiesManager.
type MockEntitiesManagerMockRecorder struct {
	mock *MockEntitiesManager
}

// NewMockEntitiesManager creates a new mock instance.
func NewMockEntitiesManager(ctrl *gomock.Controller) *MockEntitiesManager {
	mock := &MockEntitiesManager{ctrl: ctrl}
	mock.recorder = &MockEntitiesManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntitiesManager) EXPECT() *MockEntitiesManagerMockRecorder {
	return m.recorder
}

// BuildESQueryEntity mocks base method.
func (m *MockEntitiesManager) BuildESQueryEntity(selector *resmodels.EntitySelector, params *resmodels.BuildEntityESQueryParams) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildESQueryEntity", selector, params)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildESQueryEntity indicates an expected call of BuildESQueryEntity.
func (mr *MockEntitiesManagerMockRecorder) BuildESQueryEntity(selector, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildESQueryEntity", reflect.TypeOf((*MockEntitiesManager)(nil).BuildESQueryEntity), selector, params)
}

// PatchEntity mocks base method.
func (m *MockEntitiesManager) PatchEntity(selector *resmodels.EntitySelector, updates *resmodels.EntityUpdates) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchEntity", selector, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchEntity indicates an expected call of PatchEntity.
func (mr *MockEntitiesManagerMockRecorder) PatchEntity(selector, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchEntity", reflect.TypeOf((*MockEntitiesManager)(nil).PatchEntity), selector, updates)
}

// ReadAccountParents mocks base method.
func (m *MockEntitiesManager) ReadAccountParents(selector *resmodels.EntitySelector) ([]*resmodels.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAccountParents", selector)
	ret0, _ := ret[0].([]*resmodels.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAccountParents indicates an expected call of ReadAccountParents.
func (mr *MockEntitiesManagerMockRecorder) ReadAccountParents(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAccountParents", reflect.TypeOf((*MockEntitiesManager)(nil).ReadAccountParents), selector)
}

// ReadEntity mocks base method.
func (m *MockEntitiesManager) ReadEntity(selector *resmodels.EntitySelector) (*resmodels.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEntity", selector)
	ret0, _ := ret[0].(*resmodels.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEntity indicates an expected call of ReadEntity.
func (mr *MockEntitiesManagerMockRecorder) ReadEntity(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEntity", reflect.TypeOf((*MockEntitiesManager)(nil).ReadEntity), selector)
}

// ReadEntityAccounts mocks base method.
func (m *MockEntitiesManager) ReadEntityAccounts(selector *resmodels.EntityAccountsSelector) ([]*resmodels.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEntityAccounts", selector)
	ret0, _ := ret[0].([]*resmodels.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEntityAccounts indicates an expected call of ReadEntityAccounts.
func (mr *MockEntitiesManagerMockRecorder) ReadEntityAccounts(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEntityAccounts", reflect.TypeOf((*MockEntitiesManager)(nil).ReadEntityAccounts), selector)
}

// ReadEntityCustomFields mocks base method.
func (m *MockEntitiesManager) ReadEntityCustomFields(selector *resmodels.EntityCustomFieldsSelector) (*resmodels.EntityCustomFields, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEntityCustomFields", selector)
	ret0, _ := ret[0].(*resmodels.EntityCustomFields)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEntityCustomFields indicates an expected call of ReadEntityCustomFields.
func (mr *MockEntitiesManagerMockRecorder) ReadEntityCustomFields(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEntityCustomFields", reflect.TypeOf((*MockEntitiesManager)(nil).ReadEntityCustomFields), selector)
}

// ReadEntityFeatures mocks base method.
func (m *MockEntitiesManager) ReadEntityFeatures(selector *resmodels.EntitySelector) (*resmodels.EntityFeatures, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEntityFeatures", selector)
	ret0, _ := ret[0].(*resmodels.EntityFeatures)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEntityFeatures indicates an expected call of ReadEntityFeatures.
func (mr *MockEntitiesManagerMockRecorder) ReadEntityFeatures(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEntityFeatures", reflect.TypeOf((*MockEntitiesManager)(nil).ReadEntityFeatures), selector)
}
