// Code generated by MockGen. DO NOT EDIT.
// Source: product.go
//
// Generated by this command:
//
//	mockgen -source product.go -destination=./mocks/mock_product.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/loungeup/go-loungeup/client/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProductsClient is a mock of ProductsClient interface.
type MockProductsClient struct {
	ctrl     *gomock.Controller
	recorder *MockProductsClientMockRecorder
	isgomock struct{}
}

// MockProductsClientMockRecorder is the mock recorder for MockProductsClient.
type MockProductsClientMockRecorder struct {
	mock *MockProductsClient
}

// NewMockProductsClient creates a new mock instance.
func NewMockProductsClient(ctrl *gomock.Controller) *MockProductsClient {
	mock := &MockProductsClient{ctrl: ctrl}
	mock.recorder = &MockProductsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductsClient) EXPECT() *MockProductsClientMockRecorder {
	return m.recorder
}

// ReadProduct mocks base method.
func (m *MockProductsClient) ReadProduct(selector *models.ProductSelector) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadProduct", selector)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadProduct indicates an expected call of ReadProduct.
func (mr *MockProductsClientMockRecorder) ReadProduct(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadProduct", reflect.TypeOf((*MockProductsClient)(nil).ReadProduct), selector)
}

// ReadProducts mocks base method.
func (m *MockProductsClient) ReadProducts(selector *models.ProductsSelector) ([]*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadProducts", selector)
	ret0, _ := ret[0].([]*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadProducts indicates an expected call of ReadProducts.
func (mr *MockProductsClientMockRecorder) ReadProducts(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadProducts", reflect.TypeOf((*MockProductsClient)(nil).ReadProducts), selector)
}
