// Code generated by MockGen. DO NOT EDIT.
// Source: room_type.go
//
// Generated by this command:
//
//	mockgen -source room_type.go -destination=./mocks/mock_room_type.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/loungeup/go-loungeup/client/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomTypesClient is a mock of RoomTypesClient interface.
type MockRoomTypesClient struct {
	ctrl     *gomock.Controller
	recorder *MockRoomTypesClientMockRecorder
	isgomock struct{}
}

// MockRoomTypesClientMockRecorder is the mock recorder for MockRoomTypesClient.
type MockRoomTypesClientMockRecorder struct {
	mock *MockRoomTypesClient
}

// NewMockRoomTypesClient creates a new mock instance.
func NewMockRoomTypesClient(ctrl *gomock.Controller) *MockRoomTypesClient {
	mock := &MockRoomTypesClient{ctrl: ctrl}
	mock.recorder = &MockRoomTypesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomTypesClient) EXPECT() *MockRoomTypesClientMockRecorder {
	return m.recorder
}

// ReadRoomTypes mocks base method.
func (m *MockRoomTypesClient) ReadRoomTypes(selector *models.RoomTypesSelector) ([]*models.RoomType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRoomTypes", selector)
	ret0, _ := ret[0].([]*models.RoomType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRoomTypes indicates an expected call of ReadRoomTypes.
func (mr *MockRoomTypesClientMockRecorder) ReadRoomTypes(selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRoomTypes", reflect.TypeOf((*MockRoomTypesClient)(nil).ReadRoomTypes), selector)
}
